IGC: Grade Calculator (v1)
gtiosclub/CanvasPlusPlayground pull request #144
Opened 2024-12-20 14:21 UTC by rahulon12

- Built-in Grade Calculator
- Value should be the same as you would see on Canvas.

**Known Issues**
- [ ] Cannot access Grade Calculator through "Grades" view on iOS, access through "Assignments" instead.
- [ ] "Done" button above Keyboard disappears after keyboard disappears the first time on iOS

<img width="1147" alt="Screenshot 2024-12-20 at 7 47 41 PM" src="https://github.com/user-attachments/assets/6dfe5dcb-a657-4c28-8c50-56bec4055be5" />
<img width="300" alt="Simulator Screenshot - iPhone 16 Pro - 2024-12-20 at 19 50 05" src="https://github.com/user-attachments/assets/b529e365-e56f-485c-bd1d-9484f42d7a9a" />

2024-12-26 13:31 UTC, rahulon12 commented
@azooz2003-bit this is ready to review.

2024-12-26 13:32 UTC, rahulon12 commented
@azooz2003-bit @iWatger if possible, please confirm whether the values you get from the grade calc is the same as what you see on canvas

2025-01-02 05:06 UTC, azooz2003-bit requested changes

2025-01-02 09:00 UTC, azooz2003-bit commented
There's a small push to the left when typing. Very trivial tho.

![CleanShot 2025-01-02 at 11 53 22](https://github.com/user-attachments/assets/ef717126-c5cf-4921-a35f-06a2bb48cc80)

2025-01-02 09:11 UTC, azooz2003-bit requested changes

2025-01-02 09:11 UTC, azooz2003-bit commented on CanvasPlusPlayground/Features/Grades/GradeCalculator/CourseGradeCalculator.swift
> +            return earned / totalPossible
You're not weighting per assignment right? Wouldn't it be more correct to take each assignment as a percentage instead of total points. (quiz out of 8 has same weight as quiz out of 6)

2025-01-02 09:11 UTC, azooz2003-bit commented on CanvasPlusPlayground/Features/Grades/GradesViewModel.swift
> +        }
PS, I think a user may have multiple enrollments if they have multiple roles (i.e. both TA and Student), so we should remove that count == 1 check and find the enrollment with a `student` role.

2025-01-07 11:37 UTC, rahulon12 commented
Needs more thinking, closing for now.

2025-01-07 11:37 UTC, closed without merging