Create an API object for each model
gtiosclub/CanvasPlusPlayground pull request #152
Opened 2024-12-26 06:08 UTC by azooz2003-bit

The models are way too big with their 100 properties, having to implement `decode` and `encode` is burdensome. This PR will create an e.g. `CourseAPI` for `Course` which decodes the properties we like. The course is instantiated via this api object.

2024-12-29 13:53 UTC, rahulon12 requested changes

2024-12-29 13:53 UTC, rahulon12 commented on CanvasPlusPlayground/Features/Assignments/Models/SubmissionAPI.swift
Can we have a `Submission` so that we're not calling underscored variable names across the codebase, like `has_submitted_submissions`

2024-12-29 13:54 UTC, rahulon12 commented
There are wayyy too many changes here :( I think from now on we need to have large PR's like this one done in stages

2024-12-31 09:34 UTC, azooz2003-bit commented on CanvasPlusPlayground/Features/Assignments/Models/SubmissionAPI.swift
Done, lmk what u think.

2025-01-01 17:08 UTC, rahulon12 approved these changes

2025-01-01 17:09 UTC, rahulon12 commented on CanvasPlusPlayground/Features/Assignments/Models/AssignmentAPI.swift
To do during assignments implementation

2025-01-01 17:20 UTC, azooz2003-bit commented on CanvasPlusPlayground/Features/Assignments/Models/AssignmentAPI.swift
yeah separate PR

2025-01-01 18:49 UTC, merged