Calendar Fetching
gtiosclub/CanvasPlusPlayground pull request #34
Opened 2024-10-04 22:18 UTC by tejeshwar-nt

2024-10-05 06:59 UTC, tejeshwar-nt commented
https://github.com/user-attachments/assets/85e20a0d-22f1-4701-a442-b30441d9f301

2024-10-05 15:38 UTC, rahulon12 commented on CanvasPlusPlayground.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = "com.jiyoon-wd.CanvasPlusPlayground";
Could you unstage these changes?

2024-10-05 15:38 UTC, rahulon12 commented on CanvasPlusPlayground/CalendarManager.swift
I don't think this file has been added to your `project.pbxproj` file. When I pulled it doesn't show up in Xcode.

2024-10-05 15:38 UTC, rahulon12 commented on CanvasPlusPlayground/Views/CalendarView.swift
> +struct EventSection: View {
nit: 
```suggestion
private struct EventSection: View {
```

2024-10-05 15:38 UTC, rahulon12 commented on CanvasPlusPlayground/Views/CalendarView.swift
> +struct EventDetails: View {
nit:
```suggestion
private struct EventDetails: View {
```

2024-10-22 20:34 UTC, rahulon12 requested changes
We need to figure out why the date isn't appearing correctly, like we discussed in person.

2024-11-17 17:31 UTC, closed without merging